---
services:
  portainer-agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    networks:
     - localnet
    ports:
      - 9001:9001
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro