---
services:
  torrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - localnet
    env_file: ../environment.env
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG}/qbittorrent:/config:rw
      - ${DOWNLOADS}:/downloads
      - ${VIDEO}:/video:rw
      - ${BOOKS}:/books:rw
    ports:
      - 8080:8080
      - 6881:6881
    restart: unless-stopped
    labels:
      # Traefik setup
      - traefik.enable=true
      - traefik.http.routers.torrent.rule=Host(`torrent.${FQDN}`) || Host(`torrent.${VPN}`)
      - traefik.http.routers.torrent.tls=true
      - traefik.http.services.torrent.loadbalancer.server.port=8080
      # Homepage setup
      - homepage.group=Video
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=https://torrent.${FQDN}/
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://${HOST_IP}:8080
      - homepage.widget.username=${ADMIN_USER}
      - homepage.widget.password=${ADMIN_PASSWORD}
