---
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    labels:
      # Traefik Setup
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${FQDN}`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=default
      - traefik.http.services.plex.loadbalancer.server.port=32400
      # Homepage setup
      - homepage.group=Video
      - homepage.name=Plex Media Server
      - homepage.href=https://plex.${FQDN}/
      - homepage.icon=plex.png
    env_file: ../environment.env
    environment:
      - VERSION=docker
    volumes:
      - ${CONFIG}/plex:/config:rw
      - ${MOVIES}:/movies:rw
      - ${SHOWS}:/tv:rw
      - /tmp:/tmp:rw
    restart: unless-stopped
