---
name: adguardhome
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - adguard:/opt/adguardhome
    labels:
      - homepage.group=Network & System
      - homepage.name=AdGuardHome
      - homepage.icon=adguard-home.png
      - homepage.href=http://adguard.pi.home/
      - homepage.widget.type=adguard
      - homepage.widget.url=http://10.27.17.100:80
      - homepage.widget.username=admin
      - homepage.widget.password=adminadmin

volumes:
  adguard:
    name: adguard
    external: true
