services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: always
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.pi.home,10.27.17.101:3001,optiplex.tail71d46f.ts.net:3001,home.mentita.men
    ports:
      - 3001:3000
    volumes:
      - ${CONFIG}/homepage:/app/config # Make sure your local config directory exists
      - ${CONFIG}/images/background.png:/app/public/images/background.png:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
