---
services:
  mealie:
    image: docker.io/hkotel/mealie:latest
    container_name: mealie
    hostname: mealie
    depends_on: 
      - mealie-db
    ports:
      - "9000:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.pi.home
    # Database settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=mealie-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: unless-stopped
    labels:
      # Homepage setup
      - homepage.group=Home
      - homepage.name=Mealie
      - homepage.icon=mealie.png
      - homepage.href=${{ HREF }}
      - vpn.app.name=mealie
      - vpn.app.port=9000

  mealie-db:
    image: postgres:16-alpine
    container_name: mealie-db
    restart: unless-stopped
    volumes:
      - mealie-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie

volumes:
  mealie-data:
    name: mealie-data
  mealie-dbdata:
    name: mealie-dbdata
