---
services:
 plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - VERSION=docker
    volumes:
      - /tmp:/tmp:rw
      - ${CONFIG}/plex:/config:rw
      - ${ANIME}:/anime:rw
      - ${MOVIES}:/movies:rw
      - ${MVS}:/musicvids:rw
      - ${SHOWS}:/tv:rw
    restart: unless-stopped
