services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - localnet
    volumes:
      - ${CONFIG}/stirling/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ${CONFIG}/stirling/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    labels:
      # Traefik Setup
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`pdf.pi.home`)
      - traefik.http.routers.pdf.tls=true
#      - traefik.http.routers.pdf.middlewares=authentik-auth@file
      # - traefik.http.service.pdf.loadbalancer.ports=8081
      # Homepage setup
      - homepage.group=Home
      - homepage.name=Stirling PDF
      - homepage.icon=stirling-pdf.png
      - homepage.href=https://pdf.pi.home/
