---
services:
  torrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - localnet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - /home/jalvare/media/video:/video:rw
      - ${CONFIG}/qbittorrent:/config:rw
      - ${DOWNLOADS}:/downloads:rw
      - ${BOOKS}:/books:rw
    ports:
      - 8080:8080
      - 6881:6881
    restart: unless-stopped
    labels:
      # Homepage setup
      - homepage.group=Video
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=${{ HREF }}
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://10.27.17.101:8080
      - homepage.widget.username=admin
      - homepage.widget.password=adminadmin
