---
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    volumes:
      - ${CONFIG}/sonarr:/config:rw
      - ${ANIME}:/anime:rw
      - ${SHOWS}:/shows:rw
      - ${DOWNLOADS}:/downloads:rw
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      # Homepage setup
      - homepage.group=Video
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=${{ HREF }}
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://10.27.17.101:8989
      - homepage.widget.key=f5fc704826654ce282b9ef829408591e
      - vpn.app.name=sonarr
      - vpn.app.port=8989

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    env_file: .env
    volumes:
      - ${CONFIG}/radarr:/config:rw
      - ${MOVIES}:/movies:rw
      - ${DOWNLOADS}:/downloads:rw
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      # Homepage setup
      - homepage.group=Video
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=${{ HREF }}
      - homepage.widget.type=radarr
      - homepage.widget.url=http://10.27.17.101:7878
      - homepage.widget.key=34e7326d77474616a47167fefb2d5610
      - vpn.app.name=radarr
      - vpn.app.port=7878
