services:
  proxy-redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - localnet

  reverse-proxy:
    image: traefik:v3
    restart: unless-stopped
    depends_on:
      - proxy-redis
    networks:
      - localnet
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config.yaml:/etc/traefik/traefik.yaml
      - ./tls.yaml:/etc/traefik/dynamic/tls.yaml
      - ${CONFIG}/ssl:/etc/traefik/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # Traefik setup
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`proxy.${FQDN}`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certResolver=default
      - traefik.http.routers.traefik.service=traefik-svc
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080
      # Homepage setup
      - homepage.group=Network & System
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=https://proxy.${FQDN}/dashboard/
