---
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/fullchain.pem
        keyFile: /etc/traefik/certs/cert-key.pem

http:
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true