---
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine-sts
    networks:
      - localnet
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      # Traefik setup
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${FQDN}`)
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.service=portainer-svc
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certResolver=default
      - traefik.http.services.portainer-svc.loadBalancer.server.port=9443
      - traefik.http.services.portainer-svc.loadBalancer.server.scheme=https
      - traefik.http.services.portainer-svc.loadBalancer.serverstransport=insecureTransport@file
      # Homepage setup
      - homepage.group=Network & System
      - homepage.name=PortainerCE
      - homepage.icon=portainer.png
      - homepage.href=https://portainer.${FQDN}/

volumes:
  portainer_data:
    name: portainer_data
    external: true